### ISSUE TITLE
Migrate automated builds to GitHub Actions

### ISSUE THREAD

**Issue by hobu** [ASPRSorg/LAS#97]
- [x] Travis builds are slow
- [x] Use GitHub Actions artifacts to attach built PDFs and other artifacts to individual builds instead of uploading to hobu's S3 bucket
- [x] Integrate a spell checker

**Comment by esilvia** [comment]
Thanks for bringing this up. I recently noticed GitHub add this functionality and it seemed like it was designed specifically for us. Have you played around with Actions yet @hobu ? 

Since you used Docker in the implementation, it does seem like it wouldn't be too bad to migrate over, in theory. But it's never as easy as it looks.

**Comment by hobu** [comment]
> Have you played around with Actions yet @hobu ?

Yes, I have done tons of Actions stuff, and I'll port this over to use it when I get a few cycles.

**Comment by esilvia** [comment]
There's a warning about using "ubuntu-latest" after I completed the merge. Is that a concern? Or should we freeze the ubuntu version?

https://github.com/ASPRSorg/LAS/actions/runs/421953703

**Comment by esilvia** [comment]
- [ ] Also, neat usage of the checkbox functionality. I hadn't noticed them add that.

**Comment by hobu** [comment]
> There's a warning about using "ubuntu-latest" after I completed the merge. Is that a concern? Or should we freeze the ubuntu version?

It shouldn't be a problem, but you can pin to ``ubuntu-18.04`` if you are worried. See https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/ for more detail.

**Comment by esilvia** [comment]
It's just that I noticed a few subtle changes in the resultant PDF – e.g., "Continued on next page" --> "continues on next page", and paragraphs no longer break in the middle... In this case, both changes were an improvement, but I'm nervous changes might occur unnoticed simply because GitHub changed their ubuntu version.

**Comment by esilvia** [comment]
What about preempting the change by freezing it at `ubuntu-20.04` while we're still paying attention?

**Comment by esilvia** [comment]
That seems to have worked. https://github.com/ASPRSorg/LAS/commit/c073bdb91c606af8ba3603c554a0ae4e42de06d0 

I'll proceed with `ubuntu-20.04` "permanently" tagged.

@hobu Thanks for figuring this out. I love how much cleaner the source is now.

**Comment by esilvia** [comment]
Is there a way to upload the PDF directly without compressing it in a ZIP?

**Comment by manleypv** [comment]
![image](https://user-images.githubusercontent.com/36712240/105047699-42c3f280-5a30-11eb-993d-0ea25eff45c0.png)

Here? Looks like you can just drag and drop files.

**Comment by hobu** [comment]
> Is there a way to upload the PDF directly without compressing it in a ZIP?

No. GitHub artifacts can only be ZIP files. IIRC, there was some ticket traffic to relax that for a known set of content types, but it hasn't happened yet.

**Comment by manleypv** [comment]
[ManleyAcademicCV_2020.pdf](https://github.com/ASPRSorg/LAS/files/5836570/ManleyAcademicCV_2020.pdf)

**Comment by manleypv** [comment]
I guess you don't mean in these comments.

**Comment by hobu** [comment]
> I guess you don't mean in these comments.

Correct. It's annoying to have to unzip the build artifacts from the new GitHub Actions process.

**Comment by esilvia** [comment]
@manleypv I'm talking about the PDF artifact posted after the PDF builds, such as here: https://github.com/ASPRSorg/LAS/actions/runs/494923522

@hobu Thanks for confirming. I couldn't find any way to do that either.
